/**
 *  File: com.hhy.shop.biz.dal.impl.TbOrderItemDao.java
 *  Description:These codes were generated by CodeSmith.
 *  Copyright 2015-2016 greenline.group Corporation. All rights reserved.
 *  @author
 */
package com.hhy.shop.biz.dal.order.impl;

import com.hhy.shop.biz.dal.base.BaseDAO;
import com.hhy.shop.biz.dal.order.TbOrderItemDAO;
import com.hhy.shop.biz.dal.order.dataobject.TbOrderItemDO;
import org.springframework.stereotype.Repository;

import java.sql.SQLException;

/**
 * Created by eclipse.
 * User: vinfer
 * Date: 12-2-20
 * Time: 上午9:23
 * To change this template use File | Settings | File Templates.
 */
@Repository
public class TbOrderItemDAOImpl extends BaseDAO implements TbOrderItemDAO{
    /**
     * 添加
     * 
     * @param tbOrderItemDO
     * @return
     */
    @Override
    public Long add(TbOrderItemDO tbOrderItemDO) {
        return (Long) this.getSqlMapClientTemplate().insert("tbOrderItem.insert", tbOrderItemDO);
    }

    /**
     * 修改
     * 
     * @param tbOrderItemDO
     * @return
     */
    public int update(TbOrderItemDO tbOrderItemDO) {
        return this.getSqlMapClientTemplate().update("tbOrderItem.update", tbOrderItemDO);
    }

    /**
     * 根据活动id查找
     * 
     * @param id
     * @return
     */
    public TbOrderItemDO queryById(Long id) {
        return (TbOrderItemDO) this.getSqlMapClientTemplate().queryForObject("tbOrderItem.query_by_id", id);
    }
    
     @Override
    public int delete(Long id) throws SQLException {
       return this.getSqlMapClient().delete("tbOrderItem.delete", id);
        
    }
  
}