/**
 *  File: com.hhy.shop.biz.dal.impl.TbOrderShippingDao.java
 *  Description:These codes were generated by CodeSmith.
 *  Copyright 2015-2016 greenline.group Corporation. All rights reserved.
 *  @author
 */
package com.hhy.shop.biz.dal.order.impl;

import com.hhy.shop.biz.dal.order.dataobject.TbOrderShippingDO;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

import com.hhy.shop.biz.dal.order.TbOrderShippingDAO;

import java.sql.SQLException;

/**
 * Created by eclipse.
 * User: vinfer
 * Date: 12-2-20
 * Time: 上午9:23
 * To change this template use File | Settings | File Templates.
 */
@Repository
public class TbOrderShippingDAOImpl extends SqlMapClientDaoSupport implements TbOrderShippingDAO{
    /**
     * 添加
     * 
     * @param tbOrderShippingDO
     * @return
     */
    @Override
    public Long add(TbOrderShippingDO tbOrderShippingDO) {
        return (Long) this.getSqlMapClientTemplate().insert("tbOrderShipping.insert", tbOrderShippingDO);
    }

    /**
     * 修改
     * 
     * @param tbOrderShippingDO
     * @return
     */
    public int update(TbOrderShippingDO tbOrderShippingDO) {
        return this.getSqlMapClientTemplate().update("tbOrderShipping.update", tbOrderShippingDO);
    }

    /**
     * 根据活动id查找
     * 
     * @param id
     * @return
     */
    public TbOrderShippingDO queryById(Long id) {
        return (TbOrderShippingDO) this.getSqlMapClientTemplate().queryForObject("tbOrderShipping.query_by_id", id);
    }
    
     @Override
    public int delete(Long id) throws SQLException {
       return this.getSqlMapClient().delete("tbOrderShipping.delete", id);
        
    }
  
}