/**
 *  File: com.hhy.shop.biz.dal.impl.TbOrderDao.java
 *  Description:These codes were generated by CodeSmith.
 *  Copyright 2015-2016 greenline.group Corporation. All rights reserved.
 *  @author
 */
package com.hhy.shop.biz.dal.order.impl;

import com.hhy.shop.biz.dal.base.BaseDAO;
import com.hhy.shop.biz.dal.order.TbOrderDAO;
import com.hhy.shop.biz.dal.order.dataobject.TbOrderDO;
import org.springframework.stereotype.Repository;

import java.sql.SQLException;

/**
 * Created by eclipse. User: vinfer Date: 12-2-20 Time: 上午9:23 To change this
 * template use File | Settings | File Templates.
 */
@Repository
public class TbOrderDAOImpl extends BaseDAO implements TbOrderDAO {
    /**
     * 添加
     * 
     * @param tbOrderDO
     * @return
     */
    @Override
    public Long add(TbOrderDO tbOrderDO) {
        return (Long) this.getSqlMapClientTemplate().insert("tbOrder.insert", tbOrderDO);
    }

    /**
     * 修改
     * 
     * @param tbOrderDO
     * @return
     */
    public int update(TbOrderDO tbOrderDO) {
        return this.getSqlMapClientTemplate().update("tbOrder.update", tbOrderDO);
    }

    /**
     * 根据活动id查找
     * 
     * @param id
     * @return
     */
    public TbOrderDO queryById(Long id) {
        return (TbOrderDO) this.getSqlMapClientTemplate().queryForObject("tbOrder.query_by_id", id);
    }

    @Override
    public int delete(Long id) {
        try {
            return this.getSqlMapClient().delete("tbOrder.delete", id);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

}