/**
 *  File: com.hhy.shop.biz.dal.operate.dataobject.TbOrderItem.java
 *  Description:These codes were generated by CodeSmith.
 *  Copyright 2015-2016 greenline.group Corporation. All rights reserved.
 */
package com.hhy.shop.biz.dal.order.dataobject;


import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;


//tb_order_item
public class TbOrderItemDO{

  

	/**
	* 
	*/
    private String id;
    
	/**
	* 
	*/
    private String itemId;
    
	/**
	* 
	*/
    private String orderId;
    
	/**
	* 
	*/
    private Integer num;
    
	/**
	* 
	*/
    private String title;
    
	/**
	* 
	*/
    private Long price;
    
	/**
	* 
	*/
    private Long totalFee;
    
	/**
	* 
	*/
    private String picPath;
    

    public String getId() {
        return id;
    }
    
    public void setId(String id){
        this.id = id;
    }
    
    public String getItemId() {
        return itemId;
    }
    
    public void setItemId(String itemId){
        this.itemId = itemId;
    }
    
    public String getOrderId() {
        return orderId;
    }
    
    public void setOrderId(String orderId){
        this.orderId = orderId;
    }
    
    public Integer getNum() {
        return num;
    }
    
    public void setNum(Integer num){
        this.num = num;
    }
    
    public String getTitle() {
        return title;
    }
    
    public void setTitle(String title){
        this.title = title;
    }
    
    public Long getPrice() {
        return price;
    }
    
    public void setPrice(Long price){
        this.price = price;
    }
    
    public Long getTotalFee() {
        return totalFee;
    }
    
    public void setTotalFee(Long totalFee){
        this.totalFee = totalFee;
    }
    
    public String getPicPath() {
        return picPath;
    }
    
    public void setPicPath(String picPath){
        this.picPath = picPath;
    }
    

 
}
