/**
 *  File: com.hhy.shop.biz.dal.ITbOrderDAO.java
 *  Description:These codes were generated by CodeSmith.
 *  Copyright 2015-2016 greenline.group Corporation. All rights reserved.
 *  @author
 */
package com.hhy.shop.biz.dal.order;

import com.hhy.shop.biz.dal.order.dataobject.TbOrderDO;

/**
 * . User: vinfer Date: 15-2-20 Time: 上午9:21 To change this template use File |
 * Settings | File Templates.
 */
public interface TbOrderDAO {

    /**
     * 添加
     * 
     * @param tbOrderDO
     * @return
     */
    Long add(TbOrderDO tbOrderDO);

    /**
     * 修改
     * 
     * @param tbOrderDO
     * @return
     */
    int update(TbOrderDO tbOrderDO);

    /**
     * 根据活动id查找
     * 
     * @param id
     * @return
     */
    TbOrderDO queryById(Long id);

    /**
     * 根据活动id删除
     * 
     * @param id
     * @return
     */
    int delete(Long id);

}
